Repository chjuca/doit, pull requests merged in 2019-11, with the labels that each got.

#4 Terminado el login
  .idea/.name
  app/build.gradle
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/xcheko51x/agendacitas/LoginActivity.java
  app/src/main/java/com/xcheko51x/agendacitas/SplashScreen.java
  app/src/main/java/com/xcheko51x/agendacitas/data/LoginDataSource.java
  app/src/main/java/com/xcheko51x/agendacitas/data/LoginRepository.java
  app/src/main/java/com/xcheko51x/agendacitas/data/Result.java
  app/src/main/java/com/xcheko51x/agendacitas/data/model/LoggedInUser.java
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: help wanted

#15 Agregnado un archivo que da problemas en el gitignore
  .gitignore
Labels: enhancement

#18 Cambiando los colores ya arreglando los colores del Renato
  app/src/main/res/menu/activity_navegacion_drawer.xml
  app/src/main/res/values/colors.xml
Labels: bug, enhancement

#36 Agregando un acerca de
  app/src/main/res/layout/fragment_acerca_de.xml
  app/src/main/res/values/strings.xml
Labels: enhancement
